MACRO(BASICCONFIGURATION)
    # set project name
    SET(PrjName Sample_Project)

    # define libraries
    SET(PrjLibraries 
        sample_module)

    # define executables
    SET(PrjExecutables 
        sample_executable)
ENDMACRO(BASICCONFIGURATION)

MACRO(INITIALIZEEXTERNAL)
    # INIT AND COLLECT DEPENDENCIES
    INITDEPENDENCIES()
    CHECKQT5DIRSET()
    WHICHVS()
    COLLECTDEPINCLUDES()
    COLLECTDEPLIBS()
ENDMACRO(INITIALIZEEXTERNAL)

MACRO(DEFINEMODULEQTDEPENDENCY)
    SETMODULEQTTARGETSLIST(sample_executable Core Widgets Gui)
ENDMACRO(DEFINEMODULEQTDEPENDENCY)

MACRO(DEFINEMODULELINKDEPENDENCY)
    SETMODULELINKTARGETSLIST(sample_executable sample_module)
ENDMACRO(DEFINEMODULELINKDEPENDENCY)

MACRO(DEFINEEXTERNALINCLUDEDEPENDENCIES)
    # external includes are going here
ENDMACRO(DEFINEEXTERNALINCLUDEDEPENDENCIES)

MACRO(DEFINEEXTERNALLINKDEPENDENCIES)
    # external link are going here
ENDMACRO(DEFINEEXTERNALLINKDEPENDENCIES)

MACRO(DEFINEDEFINES)

ENDMACRO(DEFINEDEFINES)